server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/human_resource_office?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${LOCAL_DB_HOST}
    password: ${LOCAL_DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    repositories:
      bootstrap-mode: deferred

springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  packages-to-scan: com.github.backend.controller
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs

logging:
  config: classpath:logback-spring-local.xml